/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : KeyPad interface 4x4 Matrix
 ******************************************************************************/


#include <stdint.h>
#include <stdio.h>

void delay(void)
{
	for(uint32_t i=0; i < 300000; i++);
}

int main(void)
{
	//peripherals registers addresses
	uint32_t volatile *const pGPIOCModeReg  = (uint32_t*)(0x40020800);
	uint32_t volatile *const pInPutDataReg  = (uint32_t*)(0x40020800+0x10);
	uint32_t volatile *const pOutPutDataReg = (uint32_t*)(0x40020800+0x14);
	uint32_t volatile *const pClockCtrlReg  = (uint32_t*)(0x40023800+0x30);
	uint32_t volatile *const pPullupDownReg = (uint32_t*)(0x40020800+0x0C);

	//1.Enable the peripheral clock of GPIOC peripheral
	*pClockCtrlReg |= (1 << 2);

	//2.Configure PC0,PC1,PC2,PC3 as output (rows)
	*pGPIOCModeReg &= ~(0XFF );	//clear
	*pGPIOCModeReg |= 0x55;			//set

	//3.Configure PB12,PB13,PB14,PB15 as input (column)
	*pGPIOCModeReg &= ~(0xFF << 16); //clear

	//4.Enable internal pull-up resistor for PA8,PA9,PA10,PA11
	*pPullupDownReg &= ~(0xFF << 16);
	*pPullupDownReg |=  (0x55 << 16);

while(1)
{
	//make all rows HIGH
	*pOutPutDataReg |= 0x0f;

	//make R1 LOW(PB3)
	*pOutPutDataReg &= ~(1 << 0);

	//scan the columns
	//check C1(PB12) low or high
	if( !(*pInPutDataReg & (1 << 8))){
		//key is pressed
		delay();
		printf("1\n");
	}

	//check C2(PB13) low or high
	if( !(*pInPutDataReg & (1 << 9))){
		//key is pressed
		delay();
		printf("2\n");
	}

	//check C3(PB14) low or high
	if( !(*pInPutDataReg & (1 << 10))){
		//key is pressed
		delay();
		printf("3\n");
	}

	//check C4(PB15) low or high
	if( !(*pInPutDataReg & (1 << 11))){
		//key is pressed
		delay();
		printf("F\n");
	}


	//make all rows HIGH
	*pOutPutDataReg |= 0x0f;

	//make R2 LOW(PB4)
	*pOutPutDataReg &= ~(1 << 1);

	//scan the columns
	//check C1(PB12) low or high
	if( !(*pInPutDataReg & (1 << 8))){
		//key is pressed
		delay();
		printf("4\n");
	}

	//check C2(PB13) low or high
	if( !(*pInPutDataReg & (1 << 9))){
		//key is pressed
		delay();
		printf("5\n");
	}

	//check C3(PB14) low or high
	if( !(*pInPutDataReg & (1 << 10))){
		//key is pressed
		delay();
		printf("6\n");
	}

	//check C4(PB15) low or high
	if( !(*pInPutDataReg & (1 << 11))){
		//key is pressed
		delay();
		printf("E\n");
	}


	//make all rows HIGH
	*pOutPutDataReg |= 0x0f;

	//make R3 LOW(PB5)
	*pOutPutDataReg &= ~(1 << 2);

	//scan the columns
	//check C1(PB12) low or high
	if( !(*pInPutDataReg & (1 << 8))){
		//key is pressed
		delay();
		printf("7\n");
	}

	//check C2(PB13) low or high
	if( !(*pInPutDataReg & (1 << 9))){
		//key is pressed
		delay();
		printf("8\n");
	}

	//check C3(PB14) low or high
	if( !(*pInPutDataReg & (1 << 10))){
		//key is pressed
		delay();
		printf("9\n");
	}

	//check C4(PB15) low or high
	if( !(*pInPutDataReg & (1 << 11))){
		//key is pressed
		delay();
		printf("D\n");
	}


	//make all rows HIGH
	*pOutPutDataReg |= 0x0f;

	//make R4 LOW(PB6)
	*pOutPutDataReg &= ~(1 << 3);

	//scan the columns
	//check C1(PB12) low or high
	if( !(*pInPutDataReg & (1 << 8))){
		//key is pressed
		delay();
		printf("A\n");
	}

	//check C2(PB13) low or high
	if( !(*pInPutDataReg & (1 << 9))){
		//key is pressed
		delay();
		printf("0\n");
	}

	//check C3(PB14) low or high
	if( !(*pInPutDataReg & (1 << 10))){
		//key is pressed
		delay();
		printf("B\n");
	}

	//check C4(PB15) low or high
	if( !(*pInPutDataReg & (1 << 11))){
		//key is pressed
		delay();
		printf("C\n");
	}

}//while ends


}
